version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY}/fabricdot-webapi:${TAG:-latest}
    volumes: 
      - data:/app/wwwroot:rw
      - data:/app/logs:rw

volumes: 
  data:
    external: false