version: '3.4'

services:
  webapi:
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=${CONNECTIONSTRINGS_DEFAULT}
      - TZ=${TZ}
    ports:
      - "${WEBAPI_PORT}:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro